/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client2.panel;

import client2.MainForm;
import static client2.MainForm.client;
import static client2.panel.Game_panel.winner;

/**
 *
 * @author Maria
 */
public class Win_panel extends javax.swing.JPanel {

    private final MainForm parent;
    
    public Win_panel(MainForm p) {
        parent = p;
        initComponents();
        Congrads_button.setText("GAME OVER");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        New_game_button = new javax.swing.JButton();
        quit_butoon = new javax.swing.JButton();
        Congrads_button = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));

        New_game_button.setText("New game");
        New_game_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_game_buttonActionPerformed(evt);
            }
        });

        quit_butoon.setText("Quit");
        quit_butoon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_butoonActionPerformed(evt);
            }
        });

        Congrads_button.setText("Congratulations ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Congrads_button)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(137, 137, 137)
                            .addComponent(New_game_button))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(152, 152, 152)
                            .addComponent(quit_butoon))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(Congrads_button)
                .addGap(40, 40, 40)
                .addComponent(New_game_button)
                .addGap(18, 18, 18)
                .addComponent(quit_butoon)
                .addGap(107, 107, 107))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void quit_butoonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_butoonActionPerformed
        parent.setVisible(false);
        client.out.println("GAME#END_ALL");
        System.exit(0);
    }//GEN-LAST:event_quit_butoonActionPerformed

    private void New_game_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_game_buttonActionPerformed
        parent.setScreen(MainForm.Screen.GAME);
        client.out.println("GAME#START");
    }//GEN-LAST:event_New_game_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Congrads_button;
    private javax.swing.JButton New_game_button;
    private javax.swing.JButton quit_butoon;
    // End of variables declaration//GEN-END:variables
}
